"use client";

import * as React from "react";
import { ArrowDown, ArrowUp, Plus, RotateCcw, Trash2 } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { createDefaultSheetStructure, getSkillDefinitions, makeSheetItem, type TableConfig } from "@/lib/table-config";

function moved<T>(items: T[], index: number, direction: -1 | 1) {
  const nextIndex = index + direction;
  if (nextIndex < 0 || nextIndex >= items.length) return items;
  const next = [...items];
  [next[index], next[nextIndex]] = [next[nextIndex], next[index]];
  return next;
}

function OrderButtons({ label, index, length, onMove }: { label: string; index: number; length: number; onMove: (direction: -1 | 1) => void }) {
  return <div className="order-buttons"><Button type="button" variant="ghost" size="icon-sm" disabled={index === 0} aria-label={`Mover ${label} para cima`} onClick={() => onMove(-1)}><ArrowUp /></Button><Button type="button" variant="ghost" size="icon-sm" disabled={index === length - 1} aria-label={`Mover ${label} para baixo`} onClick={() => onMove(1)}><ArrowDown /></Button></div>;
}

function ShapeChoice({ value, title, description }: { value: string; title: string; description: string }) {
  return <Label className="setting-choice"><RadioGroupItem value={value} /><span><b>{title}</b><small>{description}</small></span></Label>;
}

export function SheetStructureSettings({ config, onChange }: { config: TableConfig; onChange: (updater: (current: TableConfig) => TableConfig) => void }) {
  const structure = config.sheetStructure;
  const skills = getSkillDefinitions(config);
  const [newAspect, setNewAspect] = React.useState("");
  const [newStress, setNewStress] = React.useState("");
  const [newConsequence, setNewConsequence] = React.useState("");
  const [newResource, setNewResource] = React.useState("");

  const changeStructure = (updater: (current: TableConfig["sheetStructure"]) => TableConfig["sheetStructure"]) => onChange((current) => ({ ...current, sheetStructure: updater(current.sheetStructure) }));

  return (
    <div className="structure-settings">
      <p className="section-hint">Mude nomes, ordem e espaços da Ficha conforme a sua Mesa precisar.</p>

      <div className="settings-grid two-columns">
        <fieldset className="plain-fieldset"><legend>Imagem da Ficha</legend><RadioGroup className="choice-grid three" value={structure.imageShape} onValueChange={(imageShape) => changeStructure((current) => ({ ...current, imageShape: imageShape as typeof current.imageShape }))}><ShapeChoice value="portrait" title="Vertical" description="Mais presença" /><ShapeChoice value="square" title="Quadrada" description="Equilibrada" /><ShapeChoice value="wide" title="Horizontal" description="Mais cenário" /></RadioGroup></fieldset>
        <Label className="switch-row"><span><b>Mostrar traduções em inglês</b><small>Português continua em primeiro plano.</small></span><Switch checked={structure.showTranslations} onCheckedChange={(showTranslations) => changeStructure((current) => ({ ...current, showTranslations }))} /></Label>
      </div>

      <fieldset className="plain-fieldset structure-labels"><legend>Nomes das seções</legend><div className="settings-grid four-columns">{(Object.entries(structure.labels) as Array<[keyof typeof structure.labels, string]>).map(([key, value]) => <Label className="field-stack" key={key}><span>{({ name: "Nome", description: "Descrição", aspects: "Aspectos", state: "Estado atual", stunts: "Façanhas", skills: "Perícias", notes: "Anotações" } as const)[key]}</span><Input value={value} maxLength={50} onChange={(event) => changeStructure((current) => ({ ...current, labels: { ...current.labels, [key]: event.target.value || value } }))} /></Label>)}</div></fieldset>

      <section className="structure-editor">
        <header><div><h3>Aspectos</h3><p>Tipos, nomes, traduções e ordem.</p></div><form onSubmit={(event) => { event.preventDefault(); if (!newAspect.trim() || structure.aspects.length >= 20) return; changeStructure((current) => ({ ...current, aspects: [...current.aspects, makeSheetItem("aspect", newAspect)] })); setNewAspect(""); }}><Input value={newAspect} maxLength={80} placeholder="Novo tipo de Aspecto" onChange={(event) => setNewAspect(event.target.value)} /><Button type="submit" variant="outline"><Plus /> Adicionar</Button></form></header>
        <ol className="structure-list">{structure.aspects.map((item, index) => <li className="structure-item named-definition" key={item.id}><OrderButtons label={item.label} index={index} length={structure.aspects.length} onMove={(direction) => changeStructure((current) => ({ ...current, aspects: moved(current.aspects, index, direction) }))} /><Label className="field-stack"><span>Nome</span><Input value={item.label} maxLength={80} onChange={(event) => changeStructure((current) => ({ ...current, aspects: current.aspects.map((aspect) => aspect.id === item.id ? { ...aspect, label: event.target.value || aspect.label } : aspect) }))} /></Label><Label className="field-stack"><span>Inglês <small>opcional</small></span><Input value={item.translation} maxLength={100} onChange={(event) => changeStructure((current) => ({ ...current, aspects: current.aspects.map((aspect) => aspect.id === item.id ? { ...aspect, translation: event.target.value } : aspect) }))} /></Label><Button type="button" variant="ghost" size="icon-sm" aria-label={`Remover ${item.label}`} onClick={() => changeStructure((current) => ({ ...current, aspects: current.aspects.filter((aspect) => aspect.id !== item.id) }))}><Trash2 /></Button></li>)}</ol>
      </section>

      <section className="structure-editor">
        <header><div><h3>Estresse</h3><p>Trilhas, caixas e Perícia que pode ampliar cada uma.</p></div><form onSubmit={(event) => { event.preventDefault(); if (!newStress.trim() || structure.stressTracks.length >= 10) return; changeStructure((current) => ({ ...current, stressTracks: [...current.stressTracks, { ...makeSheetItem("stress", newStress), boxes: 3, growth: "fixed", skillId: "" }] })); setNewStress(""); }}><Input value={newStress} maxLength={80} placeholder="Nova trilha" onChange={(event) => setNewStress(event.target.value)} /><Button type="submit" variant="outline"><Plus /> Adicionar</Button></form></header>
        <ol className="structure-list">{structure.stressTracks.map((item, index) => <li className="structure-item stress-definition" key={item.id}><OrderButtons label={item.label} index={index} length={structure.stressTracks.length} onMove={(direction) => changeStructure((current) => ({ ...current, stressTracks: moved(current.stressTracks, index, direction) }))} /><Label className="field-stack"><span>Nome</span><Input value={item.label} maxLength={80} onChange={(event) => changeStructure((current) => ({ ...current, stressTracks: current.stressTracks.map((track) => track.id === item.id ? { ...track, label: event.target.value || track.label } : track) }))} /></Label><Label className="field-stack"><span>Inglês</span><Input value={item.translation} maxLength={100} onChange={(event) => changeStructure((current) => ({ ...current, stressTracks: current.stressTracks.map((track) => track.id === item.id ? { ...track, translation: event.target.value } : track) }))} /></Label><Label className="field-stack"><span>Caixas</span><Input type="number" min={0} max={30} value={item.boxes} onChange={(event) => changeStructure((current) => ({ ...current, stressTracks: current.stressTracks.map((track) => track.id === item.id ? { ...track, boxes: Math.max(0, Math.min(30, Number(event.target.value) || 0)) } : track) }))} /></Label><Label className="field-stack"><span>Como cresce</span><Select value={item.growth} onValueChange={(growth) => changeStructure((current) => ({ ...current, stressTracks: current.stressTracks.map((track) => track.id === item.id ? { ...track, growth: growth as "fixed" | "condensed", skillId: growth === "fixed" ? "" : track.skillId } : track) }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="fixed">Quantidade fixa</SelectItem><SelectItem value="condensed">Pela Perícia</SelectItem></SelectContent></Select></Label>{item.growth === "condensed" && <Label className="field-stack"><span>Perícia</span><Select value={item.skillId || "none"} onValueChange={(skillId) => changeStructure((current) => ({ ...current, stressTracks: current.stressTracks.map((track) => track.id === item.id ? { ...track, skillId: skillId === "none" ? "" : skillId } : track) }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Nenhuma</SelectItem>{skills.map((skill) => <SelectItem key={skill.id} value={skill.id}>{skill.pt}</SelectItem>)}</SelectContent></Select></Label>}<Button type="button" variant="ghost" size="icon-sm" aria-label={`Remover ${item.label}`} onClick={() => changeStructure((current) => ({ ...current, stressTracks: current.stressTracks.filter((track) => track.id !== item.id) }))}><Trash2 /></Button></li>)}</ol>
      </section>

      <section className="structure-editor">
        <header><div><h3>Consequências</h3><p>Valor, severidade, qualificador e quando aparece.</p></div><form onSubmit={(event) => { event.preventDefault(); if (!newConsequence.trim() || structure.consequences.length >= 20) return; changeStructure((current) => ({ ...current, consequences: [...current.consequences, { ...makeSheetItem("consequence", newConsequence), value: 2, qualifier: "", availability: "always" }] })); setNewConsequence(""); }}><Input value={newConsequence} maxLength={80} placeholder="Nova Consequência" onChange={(event) => setNewConsequence(event.target.value)} /><Button type="submit" variant="outline"><Plus /> Adicionar</Button></form></header>
        <ol className="structure-list">{structure.consequences.map((item, index) => <li className="structure-item consequence-definition" key={item.id}><OrderButtons label={item.label} index={index} length={structure.consequences.length} onMove={(direction) => changeStructure((current) => ({ ...current, consequences: moved(current.consequences, index, direction) }))} /><Label className="field-stack"><span>Valor</span><Input type="number" min={0} max={20} value={item.value} onChange={(event) => changeStructure((current) => ({ ...current, consequences: current.consequences.map((consequence) => consequence.id === item.id ? { ...consequence, value: Math.max(0, Math.min(20, Number(event.target.value) || 0)) } : consequence) }))} /></Label><Label className="field-stack"><span>Severidade</span><Input value={item.label} maxLength={80} onChange={(event) => changeStructure((current) => ({ ...current, consequences: current.consequences.map((consequence) => consequence.id === item.id ? { ...consequence, label: event.target.value || consequence.label } : consequence) }))} /></Label><Label className="field-stack"><span>Qualificador</span><Input value={item.qualifier} maxLength={60} placeholder="Ex.: Extra" onChange={(event) => changeStructure((current) => ({ ...current, consequences: current.consequences.map((consequence) => consequence.id === item.id ? { ...consequence, qualifier: event.target.value } : consequence) }))} /></Label><Label className="field-stack"><span>Inglês</span><Input value={item.translation} maxLength={100} onChange={(event) => changeStructure((current) => ({ ...current, consequences: current.consequences.map((consequence) => consequence.id === item.id ? { ...consequence, translation: event.target.value } : consequence) }))} /></Label><Label className="field-stack"><span>Quando aparece</span><Select value={item.availability} onValueChange={(availability) => changeStructure((current) => ({ ...current, consequences: current.consequences.map((consequence) => consequence.id === item.id ? { ...consequence, availability: availability as "always" | "high-rating" } : consequence) }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="always">Sempre</SelectItem><SelectItem value="high-rating">Com Perícia alta</SelectItem></SelectContent></Select></Label><Button type="button" variant="ghost" size="icon-sm" aria-label={`Remover ${item.label}`} onClick={() => changeStructure((current) => ({ ...current, consequences: current.consequences.filter((consequence) => consequence.id !== item.id) }))}><Trash2 /></Button></li>)}</ol>
      </section>

      <section className="structure-editor">
        <header><div><h3>Recursos</h3><p>Contadores, textos ou marcações que pertencem à Ficha.</p></div><form onSubmit={(event) => { event.preventDefault(); if (!newResource.trim() || structure.resources.length >= 20) return; changeStructure((current) => ({ ...current, resources: [...current.resources, { ...makeSheetItem("resource", newResource), kind: "counter", minimum: 0, maximum: 10 }] })); setNewResource(""); }}><Input value={newResource} maxLength={80} placeholder="Novo recurso" onChange={(event) => setNewResource(event.target.value)} /><Button type="submit" variant="outline"><Plus /> Adicionar</Button></form></header>
        <ol className="structure-list">{structure.resources.map((item, index) => <li className="structure-item resource-definition" key={item.id}><OrderButtons label={item.label} index={index} length={structure.resources.length} onMove={(direction) => changeStructure((current) => ({ ...current, resources: moved(current.resources, index, direction) }))} /><Label className="field-stack"><span>Nome</span><Input value={item.label} maxLength={80} onChange={(event) => changeStructure((current) => ({ ...current, resources: current.resources.map((resource) => resource.id === item.id ? { ...resource, label: event.target.value || resource.label } : resource) }))} /></Label><Label className="field-stack"><span>Inglês</span><Input value={item.translation} maxLength={100} onChange={(event) => changeStructure((current) => ({ ...current, resources: current.resources.map((resource) => resource.id === item.id ? { ...resource, translation: event.target.value } : resource) }))} /></Label><Label className="field-stack"><span>Como preencher</span><Select value={item.kind} onValueChange={(kind) => changeStructure((current) => ({ ...current, resources: current.resources.map((resource) => resource.id === item.id ? { ...resource, kind: kind as "counter" | "text" | "check" } : resource) }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="counter">Contador</SelectItem><SelectItem value="text">Texto</SelectItem><SelectItem value="check">Marcar</SelectItem></SelectContent></Select></Label>{item.kind === "counter" && <><Label className="field-stack"><span>Mínimo</span><Input type="number" min={-999} max={item.maximum} value={item.minimum} onChange={(event) => changeStructure((current) => ({ ...current, resources: current.resources.map((resource) => resource.id === item.id ? { ...resource, minimum: Math.min(resource.maximum, Math.max(-999, Number(event.target.value) || 0)) } : resource) }))} /></Label><Label className="field-stack"><span>Máximo</span><Input type="number" min={item.minimum} max={999} value={item.maximum} onChange={(event) => changeStructure((current) => ({ ...current, resources: current.resources.map((resource) => resource.id === item.id ? { ...resource, maximum: Math.max(resource.minimum, Math.min(999, Number(event.target.value) || 0)) } : resource) }))} /></Label></>}<Button type="button" variant="ghost" size="icon-sm" aria-label={`Remover ${item.label}`} onClick={() => changeStructure((current) => ({ ...current, resources: current.resources.filter((resource) => resource.id !== item.id) }))}><Trash2 /></Button></li>)}</ol>
      </section>

      <fieldset className="plain-fieldset"><legend>Façanhas</legend><div className="settings-grid two-columns"><Label className="field-stack"><span>Quantidade gratuita sugerida</span><Input type="number" min={0} max={structure.stunts.maximum} value={structure.stunts.freeCount} onChange={(event) => changeStructure((current) => ({ ...current, stunts: { ...current.stunts, freeCount: Math.max(0, Math.min(current.stunts.maximum, Number(event.target.value) || 0)) } }))} /></Label><Label className="field-stack"><span>Quantidade máxima por Ficha</span><Input type="number" min={1} max={40} value={structure.stunts.maximum} onChange={(event) => changeStructure((current) => { const maximum = Math.max(1, Math.min(40, Number(event.target.value) || 1)); return { ...current, stunts: { freeCount: Math.min(current.stunts.freeCount, maximum), maximum } }; })} /></Label></div></fieldset>

      <div className="structure-reset"><div><b>Restaurar apenas esta parte</b><p>Nomes, listas e ordens voltam ao modelo do livro. As outras regras e os dados preenchidos não mudam.</p></div><AlertDialog><AlertDialogTrigger asChild><Button variant="outline"><RotateCcw /> Restaurar só a estrutura</Button></AlertDialogTrigger><AlertDialogContent size="sm"><AlertDialogHeader><AlertDialogTitle>Restaurar só a estrutura da Ficha?</AlertDialogTitle><AlertDialogDescription>Nomes, listas e ordens voltam ao Fate Condensado. As outras regras e todos os dados preenchidos permanecem como estão.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={() => changeStructure(() => createDefaultSheetStructure())}>Restaurar estrutura</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
    </div>
  );
}
